"""
Data models for TDB bot.

All core data structures used across the system.
Immutable where possible via frozen dataclasses.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Any


# ── Market Data ─────────────────────────────────────────────


@dataclass(frozen=True)
class Candle:
    """Single OHLCV candle."""

    timestamp: int       # Open time in milliseconds (UTC)
    open: float
    high: float
    low: float
    close: float
    volume: float
    symbol: str
    interval: str        # '5m', '15m', '1h'


# ── Coin Screening ──────────────────────────────────────────


@dataclass
class CoinScore:
    """Result of dynamic coin scanning."""

    symbol: str
    score: float         # Composite ranking score (0-1)
    volume_24h: float    # 24h quote volume in USDT
    atr_pct: float       # ATR as % of price on 5m
    spread_pct: float    # Bid-ask spread as %
    price: float         # Current price


# ── Signals ─────────────────────────────────────────────────


@dataclass
class Signal:
    """Trading signal generated by the 5-layer confluence system."""

    symbol: str
    direction: str          # 'LONG' or 'SHORT'
    entry_price: float
    stop_loss: float
    take_profit: float
    confluence_score: int   # 0-13
    quality: str            # 'A_PLUS', 'A', 'B', 'REJECTED'
    regime: str             # 'TRENDING', 'RANGING', etc.
    timestamp: int          # Signal generation time (ms)
    size_multiplier: float = 1.0
    metadata: dict = field(default_factory=dict)


# ── Trades ──────────────────────────────────────────────────


@dataclass
class Trade:
    """Represents a single trade from entry to exit."""

    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    signal: Signal | None = None

    # Order IDs on exchange
    entry_order_id: str = ""
    stop_order_id: str = ""
    tp_order_id: str = ""

    # Status
    status: str = "PENDING"  # PENDING, OPEN, CLOSED, CANCELLED

    # Prices
    entry_fill_price: float = 0.0
    exit_fill_price: float = 0.0

    # Position details
    position_size: float = 0.0   # In USDT notional
    margin_used: float = 0.0
    leverage: int = 20

    # P&L
    pnl: float = 0.0
    fees: float = 0.0
    net_pnl: float = 0.0

    # Timestamps
    opened_at: int = 0
    closed_at: int = 0
    close_reason: str = ""  # 'TP', 'SL', 'TRAIL', 'TIME', 'MANUAL'


# ── Position State ──────────────────────────────────────────


@dataclass
class PositionState:
    """Live state of an open position."""

    trade: Trade
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    unrealized_rr: float = 0.0
    bars_held: int = 0
    trailing_stop: float = 0.0


# ── Indicator Bundle ────────────────────────────────────────


@dataclass
class IndicatorSet:
    """All calculated indicators for a single symbol at one point in time."""

    symbol: str

    # Layer 1 — Regime
    adx: float = 0.0
    bb_width: float = 0.0
    bb_width_percentile: float = 0.0
    regime: str = "UNKNOWN"

    # Layer 2 — Trend
    ema_200_1h: float = 0.0
    ema_50_15m: float = 0.0
    trend_bias: str = "NONE"  # 'LONG', 'SHORT', 'NONE'

    # Layer 3 — RSI / Divergence
    rsi: float = 50.0
    divergence_type: str = "NONE"  # 'BULLISH_DIVERGENCE', 'BEARISH_DIVERGENCE', 'NONE'
    divergence_strength: float = 0.0

    # Layer 4 — Levels
    vwap: float = 0.0
    ema_50_5m: float = 0.0
    near_levels: list = field(default_factory=list)

    # Layer 5 — Volume
    current_volume: float = 0.0
    volume_sma_20: float = 0.0
    volume_ratio: float = 0.0

    # Layer 5b — Candle pattern
    candle_pattern: str = "NONE"

    # Execution helpers
    atr: float = 0.0
    current_price: float = 0.0
    prev_session_high: float = 0.0
    prev_session_low: float = 0.0
